// Compiled from from XPathNaming in Visokio codebase
(function(){'use strict';var k=this;
    function p(f){var n=typeof f;if("object"==n)if(f){if(f instanceof Array)return"array";if(f instanceof Object)return n;var e=Object.prototype.toString.call(f);if("[object Window]"==e)return"object";if("[object Array]"==e||"number"==typeof f.length&&"undefined"!=typeof f.splice&&"undefined"!=typeof f.propertyIsEnumerable&&!f.propertyIsEnumerable("splice"))return"array";if("[object Function]"==e||"undefined"!=typeof f.call&&"undefined"!=typeof f.propertyIsEnumerable&&!f.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
        n&&"undefined"==typeof f.call)return"object";return n};var a;f:{var m=k.navigator;if(m){var b=m.userAgent;if(b){a=b;break f}}a=""};var d=-1!=a.indexOf("Opera")||-1!=a.indexOf("OPR"),x=-1!=a.indexOf("Trident")||-1!=a.indexOf("MSIE"),h=-1!=a.indexOf("Edge"),c=-1!=a.indexOf("Gecko")&&!(-1!=a.toLowerCase().indexOf("webkit")&&-1==a.indexOf("Edge"))&&!(-1!=a.indexOf("Trident")||-1!=a.indexOf("MSIE"))&&-1==a.indexOf("Edge"),r=-1!=a.toLowerCase().indexOf("webkit")&&-1==a.indexOf("Edge");
    function g(){var f=a;if(c)return/rv\:([^\);]+)(\)|;)/.exec(f);if(h)return/Edge\/([\d\.]+)/.exec(f);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(f);if(r)return/WebKit\/(\S+)/.exec(f)}(function(){if(d&&k.opera){var f=k.opera.version;return"function"==p(f)?f():f}var f="",n=g();n&&(f=n?n[1]:"");return x&&(n=(n=k.document)?n.documentMode:void 0,n>parseFloat(f))?String(n):f})();var y=!x;function z(f,n){var e=f.tagName.toLowerCase(),w=[];n&&w.push(n);if("input"===e)"button"!==f.type&&"submit"!==f.type||w.push(q(f,"@value")),w.push(q(f,"@type"));else if("select"!==e)if("option"===e)w.push(l(f));else if("button"===e)w.push(l(f));else if("textarea"!==e)if("a"===e){var t=l(f);t||(t=q(f,"@title"));w.push(t)}else if("img"===e)(t=q(f,"@alt"))||(t=q(f,"@title")),w.push(t);else if("label"===e)w.push(l(f));else return null;w=w.filter(function(f){return!!f});return w.length?e+"["+w.join(" and ")+
    "]":e}function l(f){return q(f,"string()")}
    function q(f,n){var e=document.evaluate(n,f,null,XPathResult.STRING_TYPE,null).stringValue;if(!e||!e.length||!e.trim().length)return null;var w="normalize-space("+n+")",t=document.evaluate(w,f,null,XPathResult.STRING_TYPE,null).stringValue;if(!t||!t.length||!t.trim().length)return null;t!==e&&(n=w,e=t);40<e.length&&(n="substring("+n+", 1, 40)",e=document.evaluate(n,f,null,XPathResult.STRING_TYPE,null).stringValue);return n+"\x3d"+("'"+e.replace(/"/g,"\x26quot;")+"'")};function u(f){if(!f||!f.tagName)return null;var n;if(n=y&&f.dataset?"autName"in f.dataset?f.dataset.autName:null:f.getAttribute("data-"+"autName".replace(/([A-Z])/g,"-$1").toLowerCase()))n="*[@data-aut-name\x3d"+("'"+n.replace(/"/g,"\x26quot;")+"'")+"]";else{n=null;if(f.labels&&0<f.labels.length){var e=f.labels[0],w;n:{for(w=f;null!==w;w=w.parentNode)if(w===e){w=!0;break n}w=!1}w||(n=e.tagName,(e=l(e))&&(n+="["+e+"]"),n="@id\x3d(//"+n+"/@for)")}n=(e=z(f,n))?e:n?"*["+n+"]":null}if(!n)return null;n=
        "//"+n;for(e=f.parentNode;null!==e&&e instanceof Element;e=e.parentNode)if(w=u(e)){n=w+n;break}e=document.evaluate(n,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(w=0;w<e.snapshotLength;w++)if(e.snapshotItem(w)===f)return 0===w?n:"("+n+")["+(w+1)+"]";console.error("NAMING ERROR. No matches for: "+n);window.alert("NAMING ERROR. No matches for: "+n);return null}window.__vo_aut_buildXPath=u;}).call(window);
var COMPILATION_UUID="2015-11-18_164802_2175100663";
